export const SAMPLE_DATA = {
  nodes: [
    {
      node_id: 45,
      node_type: "issue",
      title: "Fix authentication flow",
      state: "closed",
      comment_count: 12,
      labels: ["bug", "auth"],
      created_at: "2024-01-15T10:00:00Z",
      last_activity: "2024-01-20T14:30:00Z",
    },
    {
      node_id: 78,
      node_type: "issue",
      title: "Add OAuth2 support",
      state: "open",
      comment_count: 8,
      labels: ["feature", "auth"],
      created_at: "2024-01-20T09:15:00Z",
      last_activity: "2024-02-01T16:45:00Z",
    },
    {
      node_id: 12,
      node_type: "issue",
      title: "Update dependencies",
      state: "closed",
      comment_count: 5,
      labels: ["maintenance"],
      created_at: "2024-01-10T11:30:00Z",
      last_activity: "2024-01-18T10:20:00Z",
    },
    {
      node_id: 23,
      node_type: "issue",
      title: "Performance optimization",
      state: "open",
      comment_count: 15,
      labels: ["enhancement", "performance"],
      created_at: "2024-01-18T13:45:00Z",
      last_activity: "2024-02-02T09:00:00Z",
    },
    {
      node_id: 89,
      node_type: "pr",
      title: "Implement JWT validation",
      state: "merged",
      comment_count: 20,
      labels: ["auth"],
      created_at: "2024-01-16T08:00:00Z",
      last_activity: "2024-01-22T15:30:00Z",
    },
    {
      node_id: 101,
      node_type: "pr",
      title: "Add unit tests for auth",
      state: "merged",
      comment_count: 10,
      labels: ["testing"],
      created_at: "2024-01-17T10:30:00Z",
      last_activity: "2024-01-21T11:00:00Z",
    },
    {
      node_id: 67,
      node_type: "pr",
      title: "Refactor token manager",
      state: "merged",
      comment_count: 18,
      labels: ["refactor"],
      created_at: "2024-01-19T12:00:00Z",
      last_activity: "2024-01-25T14:20:00Z",
    },
    {
      node_id: 125,
      node_type: "pr",
      title: "Security audit fixes",
      state: "open",
      comment_count: 25,
      labels: ["security"],
      created_at: "2024-01-22T09:30:00Z",
      last_activity: "2024-02-03T10:15:00Z",
    },
    {
      node_id: 151,
      node_type: "pr",
      title: "Integration testing suite",
      state: "merged",
      comment_count: 14,
      labels: ["testing"],
      created_at: "2024-01-24T11:00:00Z",
      last_activity: "2024-01-28T16:45:00Z",
    },
  ],
  refs: [
    { src_type: "issue", src: 45, tgt_type: "pr", tgt: 89, origin: "comment", ref_type: "closes", depth: 1 },
    { src_type: "issue", src: 45, tgt_type: "pr", tgt: 101, origin: "timeline", ref_type: "implements", depth: 1 },
    { src_type: "issue", src: 78, tgt_type: "issue", tgt: 45, origin: "comment", ref_type: "references", depth: 1 },
    { src_type: "issue", src: 78, tgt_type: "pr", tgt: 125, origin: "comment", ref_type: "references", depth: 1 },
    { src_type: "pr", src: 89, tgt_type: "issue", tgt: 45, origin: "timeline", ref_type: "closes", depth: 1 },
    { src_type: "pr", src: 101, tgt_type: "issue", tgt: 45, origin: "timeline", ref_type: "closes", depth: 1 },
    { src_type: "pr", src: 125, tgt_type: "issue", tgt: 23, origin: "comment", ref_type: "impacts", depth: 1 },
    { src_type: "pr", src: 125, tgt_type: "pr", tgt: 89, origin: "comment", ref_type: "references", depth: 1 },
    { src_type: "pr", src: 125, tgt_type: "pr", tgt: 67, origin: "comment", ref_type: "references", depth: 1 },
    { src_type: "pr", src: 151, tgt_type: "issue", tgt: 12, origin: "comment", ref_type: "tests", depth: 1 },
    { src_type: "pr", src: 151, tgt_type: "issue", tgt: 23, origin: "comment", ref_type: "tests", depth: 1 },
    { src_type: "pr", src: 151, tgt_type: "issue", tgt: 78, origin: "comment", ref_type: "tests", depth: 1 },
    { src_type: "pr", src: 151, tgt_type: "pr", tgt: 89, origin: "comment", ref_type: "validates", depth: 1 },
  ],
}
